apiVersion: v2
name: qdrant-wrapper
description: A wrapper chart to deploy Qdrant with a custom Internal Load Balancer
type: application
version: 0.1.0
appVersion: "1.16.3"
dependencies:
  - name: qdrant
    version: 1.16.3
    repository: https://qdrant.github.io/qdrant-helm
